### ISSUE TITLE
Multitasks share processors

### ISSUE THREAD

**Issue by rvock** [nDmitry/grunt-postcss#11]
If you have multiple postcss-tasks, the processors will be appended and shared between tasks.

Example Config:
```javascript
{
	postcss: {
		doubler: {
			options: {
				processors: [
					function(css) {
						css.eachDecl(function (decl) {
							decl.parent.prepend(decl.clone());
						});
					}
				],
			},
			src: 'test.css',
			dest: 'test-added.css'
		},
		none: {
			options: {
				processors: [],
			},
			src: 'test.css',
			dest: 'test-none.css'
		}
	}
}
```

test.css
```css
body {color: black;}
````

The resulting css-files:
test-added.css
```css
body {color: black;color: black;}
```

test-none.css
```css
body {color: black;color: black;}
```

test-none.css should be the same as test.css because no processors are listed.
